theme: jekyll-theme-architect
title: ML For Systems
google_analytics: true
site_description: Workshop on ML for Systems at NeurIPS 2026, TBA (will be December 11 or 12, 2026)
mini_site_description: Workshop on ML for Systems at NeurIPS '26, TBA (will be December 11 or 12, 2026)
workshop_name: neurips2026
mini_title: Current (2026)
